// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxjixdiihymvlclxmxku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4aml4ZGlpaHltdmxjbHhteGt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzA4NzgsImV4cCI6MjA3MzcwNjg3OH0.3LjL6W_swKceJkLkksLXoAn4S2ivjt3ypMOvMe0A5o4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});