// This file is automatically generated. Do not edit it directly.
// Using hardcoded Supabase configuration
const SUPABASE_URL = "https://jxjixdiihymvlclxmxku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4aml4ZGlpaHltdmxjbHhteGt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMzA4NzgsImV4cCI6MjA3MzcwNjg3OH0.3LjL6W_swKceJkLkksLXoAn4S2ivjt3ypMOvMe0A5o4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = {
  auth: {
    signIn: () => Promise.resolve({ data: null, error: null }),
    signOut: () => Promise.resolve({ error: null }),
    getUser: () => Promise.resolve({ data: { user: null }, error: null }),
  },
  from: (table: string) => ({
    select: () => ({
      data: null,
      error: null,
    }),
    insert: () => ({
      data: null,
      error: null,
    }),
    update: () => ({
      data: null,
      error: null,
    }),
    delete: () => ({
      data: null,
      error: null,
    }),
  }),
};